global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'apiCliente'
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'health'
    scheme: http
    metrics_path: /healthz
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'cambio_monedas'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
