name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Iniciar sesión en el registro de contenedores de GitHub
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Paso 3: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} .

      # Paso 4: Publicar la imagen en el registro de contenedores de GitHub
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

