name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_PAT }}  # Usando el PAT como secreto

    - name: Build Docker image
      run: |
        cd ClienteAPI
        docker build -t ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} .
    
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}
