name: Delivery

on:
  workflow_dispatch:  # Activación manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_PAT }}

    - name: Pull Docker image
      run: |
        docker pull ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

    - name: Run Docker container
      run: |
        docker run -d --name my-app-container ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

    - name: Wait for Prometheus to be ready
      run: |
        echo "Waiting for Prometheus to be ready..."
        sleep 10  # Ajusta el tiempo según lo necesario

    - name: Make GET request to Prometheus
      run: |
        curl -G 'http://localhost:9090/api/v1/query' --data-urlencode 'query=up'
